name: flutter_app_test
description: A new Flutter project.


publish_to: 'none' 

environment:                                                            
  sdk: '>=2.11.0 <3.0.0'

dependencies:


  cupertino_icons: ^1.0.2
  super_hero: ^1.0.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
uses-material-design: true
